//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBANHANGEntities : DbContext
    {
        public QLBANHANGEntities()
            : base("name=QLBANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bog> Bogs { get; set; }
        public virtual DbSet<ChiTietHDBan> ChiTietHDBans { get; set; }
        public virtual DbSet<DipDacBiet> DipDacBiets { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<HDBanHang> HDBanHangs { get; set; }
        public virtual DbSet<LoaiHoa> LoaiHoas { get; set; }
        public virtual DbSet<NguoiBan> NguoiBans { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
    }
}
