//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DipDacBiet
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaNgay { get; set; }
        public string ChuDe { get; set; }
    }
}
