//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hang
    {
        public int ID { get; set; }
        public string MaHang { get; set; }
        public string MaHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TenHang { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> DonGiaBan { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
        public string MaNgay { get; set; }
        public string MaNguoiBan { get; set; }
        public string NoiDungGiamGia { get; set; }
    }
}
