//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int ID { get; set; }
        public string TenDangNhap { get; set; }
        public string TenNguoiDung { get; set; }
        public string TenDem { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string MaNguoiDung { get; set; }
        public string PhanQuyen { get; set; }
    }
}
